// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Data.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = "631d8169-eee4-46b4-9ec9-c241314f4f55",
                            FirstName = "Ivan",
                            LastName = "Ivanov",
                            Phone = "0889337273"
                        },
                        new
                        {
                            Id = "e88f88c1-52ce-4175-8e04-da71c11c178a",
                            FirstName = "Petar",
                            LastName = "Petrov",
                            Phone = "0889123875"
                        },
                        new
                        {
                            Id = "2e55cde2-624f-49b0-a42a-7b8293d9d78d",
                            FirstName = "Maria",
                            LastName = "Mircheva",
                            Phone = "0882554238"
                        },
                        new
                        {
                            Id = "9d28917b-22f7-4385-b993-51197d8be91a",
                            FirstName = "Kalina",
                            LastName = "Todorova",
                            Phone = "0887514544"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
